### ISSUE TITLE
Materials are pink in 2021.3f1 (LTS)

### ISSUE THREAD

**Issue by tacman** [Unity-Technologies/UIToolkitUnityRoyaleRuntimeDemo#10]
After opening the project and allowing upgrade to happen, many objects are magenta.  I thought there was a way to upgrade the materials to a different rendering pipeline, but I can't find it.  

Since 2021.3 is now LTS, and the UI Toolkit is out of preview, and this is the demo project that's referenced in the documentation, I think  this repo should be updated to 2021.3.

Thanks.

**Comment by vvp3** [comment]
I can confirm for me it is the same

**Comment by juliaperdigueiroUnity** [comment]
The master branch is only compatible with the package version of UI Toolkit and consequently with Unity 2020.3, branch unity2021.2-update has the changes to work with newer versions of Unity.

Please use our forums for future issues or requests since we don't check the Issues part of this repo: https://forum.unity.com/forums/ui-toolkit.178/
