### ISSUE TITLE
The project is broken on 2022.1 and 2202.2

### ISSUE THREAD

**Issue by vaidasma** [Unity-Technologies/UIToolkitUnityRoyaleRuntimeDemo#9]
The project has missing components on TitleScreenManager game object

**Comment by Molder72** [comment]
yes, I confirm it is broken.

**Comment by juliaperdigueiroUnity** [comment]
The master branch is only compatible with the package version of UI Toolkit and consequently with Unity 2020.3, branch unity2021.2-update has the changes to work with newer versions of Unity.

Please use our forums for future issues or requests since we don't check the Issues part of this repo: https://forum.unity.com/forums/ui-toolkit.178/
